package com.lenahartmann00.funfacts;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Random;

class FactBook {
    //Fields or Member Variables - Properties about the object
    private String[] facts = {
            "Ants stretch when they wake up in the morning.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Mammoths still walked the earth when the Great Pyramid was being built.",
            "Retired basketball sensation Michael Jordan makes more money from Nike each year than all the Nike factory workers in Malaysia combined.",
            "The Olympic flag's colors are always red, black, blue, green, and yellow rings on a field of white. This is because at least one of those colors appears on the flag of every nation on the planet.",
            "The average lifespan of a major league baseball: 7 pitches.",
            "Dueling is legal is Paraguay as long as both parties are registered blood donors.",
            "All major league baseball umpires must wear black underwear while on the job in case their pants split.",
            "In 1920, Babe Ruth out-homered very American League team.",
            "Babe Ruth wore a cabbage leaf under his cap to keep his head cool. He changed it every two innings.",
            "Every year 56,000,000 people attend major league baseball games.",
            "In 18th century England, gambling dens employed someone whose job was to swallow the dice if there was a police raid.",
            "A Costa Rican worker who makes baseballs earns about $2,750 annually. The average American pro baseball player earns $2,377,000 per year.",
            "There are 336 dimples on a regulation golf ball. ",
            "The moon is moving away from the Earth at a tiny, although measurable, rate every year. 85 million years ago it was orbiting the Earth about 35 feet from the planet's surface.",
            "The star Antares is 60,000 times larger than our sun. If our sun were the size of a softball, the star Antares would be as large as a house.",
            "In Calama, a town in the Atacama Desert of Chile, it has never rained.",
            "At any given time, there are 1,800 thunderstorms in progress over the earth's atmosphere.",
            "Erosion at the base of Niagara Falls has caused the falls to recede approximately seven miles over the past 10,000 years.",
            "A ten-year-old mattress weighs double what it did when it was new due to debris that it absorbs over time. That debris includes dust mites (their droppings and decaying bodies), mold, millions of dead skin cells, dandruff, animal and human hair, secretions, excretions, lint, pollen, dust, soil, sand, and a lot of perspiration, which the average person loses at a rate of a quart a day. Good night!",
            "Every year 16 million gallons of oil runs off pavement into streams, rivers, and eventually, oceans in the United States. This is more oil than was spilled by the Exxon Valdez.",
            "In space, astronauts cannot cry because there is no gravity and tears can't flow.",
            "Most lipstick contains fish scales.",
            "A \"jiffy\" is an actual unit of time: 1/100th of a second.",
            "If you have three quarters, four dimes, and four pennies you have $1.19. you also have the largest possible amount of money in coins without being able to make change for a dollar.",
            "Leonardo Da Vinci invented scissors.",
            "Recycling one glass jar saves enough energy to operate a television for three hours.",
            "The cigarette lighter was invented before the match.",
            "The main library at Indiana University sinks over an inch a year. When it was designed engineers failed to take into account the weight of all the books that would occupy the building.",
            "A category three hurricane releases more energy in ten minutes that all the world's nuclear weapons combined.",
            "There is enough fuel in full jumbo jet tank to drive an average car four times around the world.",
            "An average of 100 people choke to death on ballpoint pens every year.",
            "Antarctica is the only continent without reptiles or snakes.",
            "The cruise liner Queen Elizabeth 2 moves only six inches for each gallon of fuel it burns.",
            "San Francisco cable cars are the only National Monuments that can move.",
            "February 1865 is the only month in recorded history not to have a full moon.",
            "Nutmeg is extremely poisonous if injected intravenously.",
            "A rainbow can be seen only in the morning or late afternoon. It can occur only when the sun is 40 degrees or less above the horizon.",
            "Lightning strikes the Earth 100 times every second.",
            "La Paz, Bolivia has an average annual temperature below 50 degrees Fahrenheit. However, it has never recorded a zero-degree temperature. Same for Stanley, the Falkland Islands, and Punta Arenas, Chile.",
            "There are over 87,000 Americans on waiting lists for organ transplants.",
            "Catsup leaves the bottle at a rate of 25 miles per year.",
            "Toxic house plants poison more children than household chemicals do.",
            "You are more likely to be infected by flesh-eating bacteria than you are to be struck by lightning.",
            "According to Genesis 1:20-22, the chicken came before the egg.",
            "Like fingerprints, everyone's tongue print is different.",
            "Your heart beats over 100,000 times a day.",
            "It takes approximately 12 hours for food to entirely digest.",
            "A sneeze travels out your mouth at over 100 m.p.h.",
            "Women blink nearly twice as often as men.",
            "Most of the dust particles in your house are dead skin.",
            "There is a company that will (for $14,000) take your ashes and compress them into a synthetic diamond to be set in jewelry for a loved one.",
            "There are more living organisms on the skin of a single human being than there are human beings on the surface of the earth.",
            "The longest bout of hiccups lasted nearly 69 years.",
            "Babies is born without kneecaps. They appear between the ages of 2 and 6.",
            "Men can read smaller print than women. Women can hear better.",
            "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
            "If you sneeze too hard you can fracture a rib. If you try to suppress a sneeze you can rupture a blood vessel in your head or neck and die. If you keep your eyes open by force they can pop out.",
            "A kiss stimulates 29 muscles and chemicals that cause relaxation. Women seem to like light and frequent kisses while men like them more strenuous.",
            "Every time you lick a stamp, you're consuming 1/10 of a calorie.",
            "Our eyes are always the same size from birth, but our nose and ears never stop growing.",
            "The average person falls asleep in seven minutes.",
            "Almost everyone who reads this will try to lick their elbow.",
            "According to Chinese acupuncture, there is a point on the head that you can press to control your appetite. It is located in the hollow just in front of the flap of the ear.",
            "In a recent survey, Americans revealed that banana was their favorite smell.",
            "The two-foot long bird called a Kea that lives in New Zealand likes to eat the strips of rubber around car windows.",
            "Snakes are true carnivores as they eat nothing but other animals. They do not eat any type of plant material.",
            "The Weddell seal can travel underwater for seven miles without surfacing for air.",
            "According to tests made at the Institute for the Study of Animal Problems in Washington, D.C., dogs and cats, like people, are either right-handed or left-handed—that is, they favor either their right or left paws.",
            "An iguana can stay under water for 28 minutes.",
            "Crocodiles and alligators are surprisingly fast on land. Although they are rapid, they are not agile, so if you ever find yourself chased by one, run in a zigzag line. You'll lose him or her every time.",
            "Horses can't vomit.",
            "A crocodile cannot stick its tongue out.",
            "Butterflies taste with their feet.",
            "Penguins can jump as high as six feet in the air.",
            "All polar bears are left-handed.",
            "An eagle can kill a young deer and fly carrying it.",
            "It was discovered on a space mission that a frog can throw up. The frog vomits its entire stomach out so the organ is dangling out of its mouth. Then the frog uses its forearms to dig out all of the stomach's contents and swallows the stomach back down again.",
            "The leg bones of a bat are so thin that no bat can walk.",
            "The katydid bug hears through holes in its hind legs.",
            "Slugs have four noses.",
            "Ostriches stick their heads in the sand to look for water.",
            "In a study of 200,000 ostriches over a period of 80 years there were no reported cases of an ostrich burying its head in the sand.",
            "It's possible to lead a cow upstairs, but not downstairs.",
            "A shrimp's heart is in its head.",
            "A snail can sleep for three years.",
            "The chicken is one of the few things that man eats before it's born and after it's dead.",
            "Some dogs can predict when a child will have an epileptic seizure and even protect the child from injury. They're not trained to do this, they simply learn to respond after observing at least one attack.",
            "A pregnant goldfish is called a twit.",
            "Rats multiply so quickly that in 18 months, two rats could have over a million descendants.",
            "There are only three types of snakes on the island of Tasmania and all three are deadly poisonous.",
            "It is physically impossible for pigs to look up into the sky.",
            "Dolphins sleep with one eye open.",
            "A goldfish has a memory span of three seconds.",
            "A shark is the only fish that can blink with both eyes.",
            "Emus and kangaroos cannot walk backwards and are on the Australian coat of arms for that reason.",
            "The jellyfish is 95% water.",
            "A hippo can open its mouth wide enough to fit a 4 foot tall child inside.",
            "Only female mosquitoes bite.",
            "Most elephants weigh less than the tongue of the blue whale.",
            "Kotex was first manufactured as bandages, during WWI.",
            "In the 16th and 17th centuries in the country of Turkey, anyone caught drinking coffee was put to death.",
            "Abraham Lincoln's dog, Fido, was also assassinated.",
            "In England, the Speaker of the House is not allowed to speak.",
            "About 3,000 years ago, most Egyptians died by the time they were 30.",
            "The first known contraceptive was crocodile dung, used by Egyptians in 2000 B.C.",
            "If a statue in the park of a person on a horse has both front legs in the air, the person died in battle. If the horse has one front leg in the air, the person died as a result of wounds received in battle. If the horse has all four legs on the ground, the person died of natural causes.",
            "The youngest pope was 11 years old.",
            "Richard Versalle, a tenor performing at New York's Metropolitan Opera House, suffered a heart attack and fell 10 feet from a ladder to the stage just after singing the line, \"You can only live so long.\"",
            "60.7 percent of eligible voters participated in the 2004 presidential election, the highest percentage in 36 years. However, more than 78 million did not vote. This means President Bush was re-elected by less than 31% of all eligible voters in the United States.",
            "David Bowie used to think he was being stalked by someone who is dressed like a giant pink rabbit. Bowie noticed the fan at several recent concerts, but became alarmed when he got on a plane and the bunny was also on board.",
            "Dr. Samuel A. Mudd was the physician who set the leg of Lincoln's assassin, John Wilkes Booth, and whose shame created the expression for ignominy: \"His name is Mudd.\"",
            "<em>Wayne's World</em> was filmed in two weeks.",
            "The first Fords had engines made by Dodge.",
            "In Ancient Egypt , priests plucked every hair from their bodies, including their eyebrows and eyelashes.",
            "More than 8,100 US troops are still listed as missing in action from the Korean War.",
            "As of January 1, 2004, the population of the United States increases by one person every 12 seconds. There is a birth every eight seconds, an immigrant is added every 25 seconds, and a death every 13 seconds.",
            "Inn the great fire of 1666, half of London was burnt down but only six people were injured.",
            "Toto was paid $125 per week while filming <em>The Wizard of Oz</em>.",
            "The only member of the band ZZ Top without a beard has the last name Beard.",
            "The electric chair was invented by a dentist.",
            "In Egypt around 1500 B.C., a shaved head was considered the ultimate in feminine beauty. Egyptian women removed every hair from their heads with special gold tweezers and polished their scalps to a high sheen with buffing cloths.",
            "George Lumley, aged 104, married Mary Dunning, aged 10, in Nortallerton, England on August 25, 1783. She was the great-great granddaughter of the woman who'd broken her engagement to Lumley, eighty years before.",
            "In Elizabethan England, the spoon was so novel and prized that people carried their own folding spoons to banquets.",
            "It costs more to buy a new car today in the United States than it cost Christopher Columbus to equip and undertake three voyages to and from the New World.",
            "Ancient Egyptians slept on pillows made of stone.",
            "Millie the White House dog earned more than four times as President Bush in 1991.",
            "A law passed in Nebraska in 1912 set hard rules of the road. Drivers in the country at night were required to stop every 150 yards, send up a skyrocket, then wait eight minutes for the road to clear before proceeding cautiously, all the while blowing their horn and shooting off flares.",
            "Louis XIV of France really was as unpleasant a fellow as he's been depicted. In 1674, when he was visiting a school at Clermont, he heard from the school's authorities that one of the children, a nine- year-old Irish lad named Francis Seldon, had made a pun about the king's bald head.<br />Louis was furious. He had a secret warrant drawn up for the child's arrest, and young Seldon was thrown into solitary confinement in the Bastille. His parents, members of one of Europe's richest merchant families, were told simply that the child had disappeared. Days turned to months, months to years, and Louis himself passed away. But Francis spent sixty-nine years \"in the hole\" for making fun of the king's baldness.",
            "The microwave was invented after a researcher walked by a radar tube and the chocolate bar in his pocket melted.",
            "23% of all photocopier faults world-wide are caused by people sitting on them and photocopying their butts.",
            "\"Stewardesses\" is the longest word that is typed using only the left hand.",
            "71% of office workers stopped on the street for a survey agreed to give up their computer passwords in exchange for a chocolate bar.",
            "The electric chair was invented by a dentist.",
            "A Boeing 767 airliner is made of 3,100,000 separate parts.",
            "The first FAX machine was patented in 1843, 33 years before Alexander Graham Bell demonstrated the telephone.",
            "Hershey's Kisses are called that because the machine that makes them looks like it's kissing the conveyor belt.",
            "\"Typewriter\" is the longest word that can be made using the keys on only one row of the keyboard.",
            "In 1980, there was only one country in the world with no telephones: Bhutan.",
            "More than 50% of the people in the world have never made or received a telephone call.",
            "No word in the English language rhymes with month, orange, silver, or purple.",
            "The \"sixth sick sheik's sixth sheep's sick\" is said to be the toughest tongue twister in the English language.",
            "\"Go,\" is the shortest complete sentence in the English language.",
            "The phrase \"rule of thumb\" is derived from an old English law which stated that you couldn't beat your wife with anything wider than your thumb.",
            "The term \"the whole 9 yards\" came from WWII fighter pilots in the South Pacific. When arming their airplanes on the ground, the .50 caliber machine gun ammo belts measured exactly 27 feet, before being loaded into the fuselage. If the pilots fired all their ammo at a target, it got \"the whole 9 yards.\"",
            "There are only four words in the English language which end in \"-dous\": tremendous, horrendous, stupendous, and hazardous.",
            "The word \"testify\" is based on the Ancient Roman practice of making men swear on their testicles when making a statement in court.",
            "In England in the 1880s, \"pants\" was considered a dirty word.",
            "According to many language experts, the most difficult kind of phrase to create is a palindrome, a sentence or group of sentences that reads the same backward and forward. A few examples:<br /><br />Red rum, sir, is murder.<br /><br />Ma is as selfless as I am.<br /><br />Nurse, I spy gypsies. Run!<br /><br />A man, a plan, a canal - Panama.<br /><br />He lived as a devil, eh?",
            "The dot that appears over the letter i is called a \"tittle.\"",
            "If you were to spell out numbers, you would you have to go until 1,000 until you would find the letter A. ",
            "Montpelier,VT is the only U.S.state capital without a McDonalds.",
            "There is a bar in London that sells vaporized vodka, which is inhaled instead of sipped.",
            "In the White House, there are 13,092 knives, forks, and spoons.",
            "Americans on average eat 18 acres of pizza every day.",
            "Coca-cola was originally green.",
            "The only food that does not spoil: honey.",
            "The Pilgrims ate popcorn at the first Thanksgiving dinner.",
            "Iceland consumes more Coca-Cola per capita than any other nation.",
            "Almonds are members of the peach family.",
            "Cranberry is the only Jell-O flavor that contains real fruit flavoring.",
            "The drive-through line on opening day at the McDonald's restaurant in Kuwait City, Kuwait was seven miles long at its peak.",
            "American Airlines saved $40,000 in 1987 by eliminating one olive from each salad served first class.",
            "Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it to begin with.",
            "The average American drinks about 600 sodas a year. ",
            "Number of US states that claim hmtl scores in their elementary schools are above national average: 50.",
            "One in every four Americans has appeared on television.",
            "In 1998, more fast-food employees were murdered on the job than police officers. ",
            "There are more collect calls on Father's Day than any other day of the year.",
            "Title 14, Section 1211, of the Code of Federal Regulations, implemented on July 16, 1969, makes it illegal for U. S. citizens to have any contact with extraterrestrials or their vehicles.",
            "There are more cars in Southern California than there are cows in India.",
            "Percentage of Americans who say that God has spoken to them: 36.",
            "Average number of people airborne over the US any given hour: 61,000.",
            "Portion of land in the US owned by the government: 1/3.",
            "Ninety percent of New York City cabbies are recently arrived immigrants.",
            "In 21 states, Wal-Mart is the single largest employer.",
            "It's against the law in Kansas to catch fish with your bare hands.",
            "Maine is the only state a one-syllable name.",
            "There are 2,000,000 millionaires in the United States.",
            "The United States has five percent of the world's population, but twenty-five percent of the world's prison population.",
            "It is illegal to hunt camels in the state of Arizona.",
            "In the United States, a pound of potato chips costs two hundred times more than a pound of potatoes.",
            "More than 2 billion pencils are manufactured each year in the United States. If these were laid end to end they would circle the world nine times. The average lead pencil will draw a line 35 miles long or write approximately 50,000 English words.",
            "Mailmen in Russia now carry revolvers after a recent decision by the government.",
            "One out of five people in the world (1.1 billion people) live on less than $1 per day.",
            "Quebec City, Canada, has about as much street crime as Disney World.",
            "The largest ocean liners pay a $250,000 toll for each trip through the Panama Canal. The canal generates fully one-third of Panama's entire economy.",
            "In every episode of Seinfeld there is a Superman somewhere.",
            "The Spanish word <em>esposa</em> means \"wife.\" The plural, <em>esposas</em>, means \"wives\", but also \"handcuffs\"",
            "City with the most Rolls Royces per capita: Hong Kong.",
            "Of the six men who made up the Three Stooges, three of them were real brothers (Moe, Curly and Shemp).",
            "If Barbie were life-size, her measurements would be 39-23-33. She would stand 7 feet, 2 inches tall.",
            "On average, people fear spiders more than they do death.",
            "Thirty-five percent of the people who use personal ads for dating are already married.",
            "In Tokyo you can buy a toupee for your dog.",
            "A dime has 118 ridges around the edge."};

    private Queue<Integer> lastShownFacts = new LinkedList<>();
    private static final int MAX_SIZE_LAST_SHOWN_FACTS = 10;

    String getFact() {
        int randomNumber = createRandomNumberNotLatelyShown();
        updateLastShownFacts(randomNumber);
        return facts[randomNumber];
    }

    private int createRandomNumberNotLatelyShown() {
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(facts.length);
        while (lastShownFacts.contains(randomNumber)) {
            randomNumber = randomGenerator.nextInt(facts.length);
        }
        return randomNumber;
    }

    private void updateLastShownFacts(int randomNumber) {
        lastShownFacts.add(randomNumber);
        if (lastShownFacts.size() >= MAX_SIZE_LAST_SHOWN_FACTS) {
            lastShownFacts.remove();
        }
    }
}
